/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameProjectUNO;

import java.awt.Font;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rashmika
 */
public class AddPlayerNameDefault extends javax.swing.JFrame {

    /**
     * Creates new form AddPlayerNameDefault
     */
    public ArrayList<String> playerNames;
    int [] score=new int [10];
    public AddPlayerNameDefault() {
        initComponents();
        playerNames=new ArrayList<>();
    }

    
    public String[] getPlayerNames(){
        playerNames.add("Corona");
        String[] playnames=playerNames.toArray(new String[playerNames.size()]);
        return playnames;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DoneButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        NameofPlayer = new javax.swing.JLabel();
        AddPlayersNames = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(750, 500));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(null);

        DoneButton.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        DoneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameProjectUNO/UNOimages/buttons/DONE_BUTTON.png"))); // NOI18N
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DoneButton);
        DoneButton.setBounds(460, 390, 200, 80);

        jTextField1.setFont(new java.awt.Font("Jokerman", 1, 36)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(350, 120, 330, 60);

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameProjectUNO/UNOimages/buttons/BACK_BUTTON.png"))); // NOI18N
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(82, 391, 200, 80);

        NameofPlayer.setFont(new java.awt.Font("Jokerman", 1, 36)); // NOI18N
        NameofPlayer.setForeground(new java.awt.Color(255, 255, 255));
        NameofPlayer.setText("PLAYER NAME:");
        jPanel1.add(NameofPlayer);
        NameofPlayer.setBounds(40, 120, 310, 55);

        AddPlayersNames.setFont(new java.awt.Font("Jokerman", 1, 48)); // NOI18N
        AddPlayersNames.setForeground(new java.awt.Color(255, 255, 255));
        AddPlayersNames.setText("!*ADD THE PLAYER NAME*!");
        jPanel1.add(AddPlayersNames);
        AddPlayersNames.setBounds(10, 10, 750, 74);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameProjectUNO/UNOimages/themes/RED.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 750, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        if(jTextField1.getText().isEmpty()) {
            PlayGame pg=new PlayGame();
            try{
                    pg.playMusicStarts("sounds/error.wav");
                } catch (IOException ex) {
                    Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedAudioFileException ex) {
                    Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            JLabel message = new JLabel("Please Enter a name!");
            message.setFont(new Font("Arial",Font.BOLD,42));
            JOptionPane.showMessageDialog(null,message);
        }
        
        else {
            String name = jTextField1.getText().trim();
            playerNames.add(name);
            if(playerNames.size()==1)
                jLabel3.setText(playerNames.get(0));
            PlayGame pg= new PlayGame();
            try {
                    pg.playMusicStarts("sounds/welcome.wav");
            } catch (IOException ex) {
                    Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (LineUnavailableException ex) {
                    Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedAudioFileException ex) {
                    Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            ImageIcon icon=new ImageIcon(AddPlayersNames.class.getResource("UNOimages/challenger/challenger.png"));
                JLabel message = new JLabel("Welcome to UNO "+playerNames.get(0));
                message.setFont(new Font("Arial",Font.BOLD,42));
                JOptionPane.showMessageDialog(null,message,"Welcome Message",JOptionPane.INFORMATION_MESSAGE,icon);
            
            }
        PlayGame pg= new PlayGame();
        try {
            pg.playMusicStarts("sounds/click.wav");
        } catch (IOException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
       new DefaultPlayer(playerNames,score).setVisible(true);
        
    }//GEN-LAST:event_DoneButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        PlayGame pg= new PlayGame();
        try {
            pg.playMusicStarts("sounds/click.wav");
        } catch (IOException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        PlayMode back =new PlayMode();
        back.setVisible(true); //used to go back to the PlayMode
    }//GEN-LAST:event_BackButtonActionPerformed

    public int p=0;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPlayerNameDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPlayerNameDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPlayerNameDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPlayerNameDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPlayerNameDefault().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddPlayersNames;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton DoneButton;
    private javax.swing.JLabel NameofPlayer;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
