/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameProjectUNO;

import java.awt.Font;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rashmika
 */
public class AddTwoPlayersNames extends javax.swing.JFrame {

    public ArrayList<String> playerNames;
    int [] score= new int [10];
    /**
     * Creates new form AddTwoPlayersNames
     */
    public AddTwoPlayersNames() {
        initComponents();
        playerNames=new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NameofPlayer = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        DoneButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddPlayersNames = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(830, 560));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(790, 560));
        jPanel1.setLayout(null);

        NameofPlayer.setFont(new java.awt.Font("Jokerman", 1, 36)); // NOI18N
        NameofPlayer.setForeground(new java.awt.Color(255, 255, 255));
        NameofPlayer.setText("PLAYER NAME:");
        jPanel1.add(NameofPlayer);
        NameofPlayer.setBounds(50, 130, 299, 55);

        jTextField1.setFont(new java.awt.Font("Jokerman", 1, 36)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(360, 130, 370, 60);

        DoneButton.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        DoneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameProjectUNO/UNOimages/buttons/DONE_BUTTON.png"))); // NOI18N
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DoneButton);
        DoneButton.setBounds(560, 390, 200, 80);

        BackButton.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameProjectUNO/UNOimages/buttons/BACK_BUTTON.png"))); // NOI18N
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(300, 390, 200, 80);

        SaveButton.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameProjectUNO/UNOimages/buttons/SAVE_BUTTON.png"))); // NOI18N
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SaveButton);
        SaveButton.setBounds(40, 390, 200, 80);

        jLabel3.setFont(new java.awt.Font("Jokerman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 250, 200, 60);

        jLabel5.setFont(new java.awt.Font("Jokerman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(450, 250, 200, 60);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("SAVE THE NAMES AFTER ENTERING AND FINALLY CLICK DONE BUTTON TO CONTINUE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 480, 720, 36);

        AddPlayersNames.setFont(new java.awt.Font("Jokerman", 1, 48)); // NOI18N
        AddPlayersNames.setForeground(new java.awt.Color(255, 255, 255));
        AddPlayersNames.setText("!*ADD TWO PLAYERS NAMES*!");
        jPanel1.add(AddPlayersNames);
        AddPlayersNames.setBounds(0, 20, 810, 74);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameProjectUNO/UNOimages/themes/RED.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 830, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    public int p=0;
    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        if (playerNames.size()==1 || playerNames.size()==0){
            JLabel message = new JLabel("Whoops! there should be atleast two players");
            message.setFont(new Font("Arial",Font.BOLD,42));
            JOptionPane.showMessageDialog(null,message);
            jTextField1.setText("");
        }
        else{
            PlayGame pg= new PlayGame();
        try {
            pg.playMusicStarts("sounds/click.wav");
        } catch (IOException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
            this.dispose();
            new MultiPlayerGameStage(playerNames,score).setVisible(true);
        }

    }//GEN-LAST:event_DoneButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        PlayGame pg= new PlayGame();
        try {
            pg.playMusicStarts("sounds/click.wav");
        } catch (IOException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        PlayMode back =new PlayMode();
        back.setVisible(true); //used to go back to the PlayMode

    }//GEN-LAST:event_BackButtonActionPerformed
    
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed

        if(jTextField1.getText().isEmpty()) {
            JLabel message = new JLabel("Please Enter a name!");
            message.setFont(new Font("Arial",Font.BOLD,42));
            JOptionPane.showMessageDialog(null,message);
        }
        else {
            String name = jTextField1.getText().trim();
            playerNames.add(name);
            if(playerNames.size()==1)
                jLabel3.setText(playerNames.get(0));

            else if(playerNames.size()==2){
                jLabel3.setText(playerNames.get(0));
                jLabel5.setText(playerNames.get(1));
            }

            if (playerNames.size()>0 && playerNames.size()<3){
                PlayGame pg= new PlayGame();
                try {
                       pg.playMusicStarts("sounds/welcome.wav");
                } catch (IOException ex) {
                       Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
                } catch (LineUnavailableException ex) {
                       Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedAudioFileException ex) {
                       Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
                ImageIcon icon=new ImageIcon(AddPlayersNames.class.getResource("UNOimages/challenger/challenger.png"));
                JLabel message = new JLabel("Welcome to UNO "+playerNames.get(p));
                message.setFont(new Font("Arial",Font.BOLD,42));
                JOptionPane.showMessageDialog(null,message,"Welcome Message",JOptionPane.PLAIN_MESSAGE,icon);
                jTextField1.setText("");
                
                p++;
            }
            if(playerNames.size()==3){
                playerNames.remove(name);
                JLabel message = new JLabel("Whoops there can be only 2 players");
                message.setFont(new Font("Arial",Font.BOLD,42));
                JOptionPane.showMessageDialog(null,message);
                jTextField1.setText("");
            }
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTwoPlayersNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTwoPlayersNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTwoPlayersNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTwoPlayersNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTwoPlayersNames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddPlayersNames;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton DoneButton;
    private javax.swing.JLabel NameofPlayer;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
