/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameProjectUNO;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author Rashmika
 */
public class PlayMode extends javax.swing.JFrame {

    /**
     * Creates new form PlayMode
     */
    public PlayMode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SinglePlayerButton = new javax.swing.JButton();
        TwoPlayerButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        ThreePlayerButton = new javax.swing.JButton();
        FourPlayerButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(790, 550));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Jokerman", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("*!CHOOSE PLAYER MODE!*");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 730, 91);

        SinglePlayerButton.setFont(new java.awt.Font("Jokerman", 1, 48)); // NOI18N
        SinglePlayerButton.setForeground(new java.awt.Color(255, 255, 255));
        SinglePlayerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameProjectUNO/UNOimages/buttons/vsPC.gif"))); // NOI18N
        SinglePlayerButton.setBorder(null);
        SinglePlayerButton.setBorderPainted(false);
        SinglePlayerButton.setContentAreaFilled(false);
        SinglePlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinglePlayerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SinglePlayerButton);
        SinglePlayerButton.setBounds(30, 210, 150, 113);

        TwoPlayerButton.setFont(new java.awt.Font("Jokerman", 1, 48)); // NOI18N
        TwoPlayerButton.setForeground(new java.awt.Color(255, 255, 255));
        TwoPlayerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameProjectUNO/UNOimages/buttons/2_PLAYERS.gif"))); // NOI18N
        TwoPlayerButton.setBorder(null);
        TwoPlayerButton.setBorderPainted(false);
        TwoPlayerButton.setContentAreaFilled(false);
        TwoPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoPlayerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(TwoPlayerButton);
        TwoPlayerButton.setBounds(220, 210, 150, 113);

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameProjectUNO/UNOimages/buttons/BACK_BUTTON.png"))); // NOI18N
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(300, 430, 201, 79);

        ThreePlayerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameProjectUNO/UNOimages/buttons/3_PLAYERS.gif"))); // NOI18N
        ThreePlayerButton.setBorder(null);
        ThreePlayerButton.setBorderPainted(false);
        ThreePlayerButton.setContentAreaFilled(false);
        ThreePlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreePlayerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ThreePlayerButton);
        ThreePlayerButton.setBounds(410, 210, 154, 113);

        FourPlayerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameProjectUNO/UNOimages/buttons/4_PLAYERS.gif"))); // NOI18N
        FourPlayerButton.setBorder(null);
        FourPlayerButton.setBorderPainted(false);
        FourPlayerButton.setContentAreaFilled(false);
        FourPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourPlayerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(FourPlayerButton);
        FourPlayerButton.setBounds(610, 210, 147, 114);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameProjectUNO/UNOimages/themes/RED.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 790, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SinglePlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinglePlayerButtonActionPerformed
        PlayGame pg=new PlayGame();
        try {
            pg.playMusicStarts("sounds/click.wav");
        } catch (IOException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        new AddPlayerNameDefault().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SinglePlayerButtonActionPerformed

    private void TwoPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoPlayerButtonActionPerformed
        
        PlayGame pg=new PlayGame();
        try {
            pg.playMusicStarts("sounds/click.wav");
        } catch (IOException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        new AddTwoPlayersNames().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TwoPlayerButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        PlayGame pg=new PlayGame();
        try {
            pg.playMusicStarts("sounds/click.wav");
        } catch (IOException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        GameMenu back =new GameMenu();
        back.setVisible(true); //used to go back to the menu
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ThreePlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreePlayerButtonActionPerformed
        PlayGame pg=new PlayGame();
        try {
            pg.playMusicStarts("sounds/click.wav");
        } catch (IOException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        new AddThreePlayersNames().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_ThreePlayerButtonActionPerformed

    private void FourPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourPlayerButtonActionPerformed
        PlayGame pg=new PlayGame();
        try {
            pg.playMusicStarts("sounds/click.wav");
        } catch (IOException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        new AddPlayersNames().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FourPlayerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayMode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton FourPlayerButton;
    private javax.swing.JButton SinglePlayerButton;
    private javax.swing.JButton ThreePlayerButton;
    private javax.swing.JButton TwoPlayerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
