/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameProjectUNO;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;

/**
 *
 * @author Rashmika
 */
public class StartUp extends javax.swing.JFrame {

    /**
     * Creates new form StartUp
     */
    StartUp window;
     //PlayGame pg= new PlayGame();
    public StartUp(){
        initComponents();
        PlayGame pg=new PlayGame();
        try {
            pg.soundLoop("sounds/background.wav");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(StartUp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(StartUp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(StartUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TapButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(920, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        TapButton.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        TapButton.setForeground(new java.awt.Color(255, 153, 0));
        TapButton.setText("TAP ANYWHERE TO CONTINUE...");
        TapButton.setBorder(null);
        TapButton.setBorderPainted(false);
        TapButton.setContentAreaFilled(false);
        TapButton.setFocusPainted(false);
        TapButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TapButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        TapButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TapButtonActionPerformed(evt);
            }
        });
        getContentPane().add(TapButton);
        TapButton.setBounds(10, 30, 910, 450);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameProjectUNO/UNOimages/icons/MENU.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(930, 495));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 920, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void TapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TapButtonActionPerformed
        PlayGame pg=new PlayGame();
        try {
            pg.playMusicStarts("sounds/click.wav");
        } catch (IOException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        new GameMenu().setVisible(true);
    }//GEN-LAST:event_TapButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TapButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void setIcon(ImageIcon imageIcon) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
